#!/bin/bash
## curl-basic-auth
## - http basic authenication example using 
##   curl in bash
## version 0.0.1
##################################################
. ${SH2}/cecho.sh		# colored echo
curl-basic-auth() {
  cecho yellow url: ${url}
  local username
  local passwd
  . ${FUNCNAME}-config.sh # ${username}, ${passwd}
  curl -v -u ${username}:${password} ${url} --location
}
##################################################
if [ ${#} -eq 1 ] 
then
 url="${1}"
else
 exit 1 # wrong args
fi
##################################################
curl-basic-auth
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 27 Jan 2019 14:04:18 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
