#!/bin/bash
## curl-example
## - submits form with csrf protection 
## version 0.0.1 - initial
##################################################
. ${SH2}/aliases/commands.sh	# subcommands
## specially crafted bash curl boilerplate for this example 
template-command-curl() { { local method ; method="${1}" ; } 
  { 
    command curl ${url} \ 
    if-headers \ 
    if-data \ 
    if-options 
  } | tee ${method}-response  
} 
curl-head() { { local url ; url="${url}" ; } 
   template-command-curl \ 
   head  
} 
curl-get() { { local url ; url="${url}" ; } 
   template-command-curl \ 
   get 
} 
## setup curl 
if-headers() { true ; } 
if-data() { true ; } 
if-options() { true ; } 
curl-post() { { local url ; url="${url}" ; } 
  template-command-curl \ 
  post 
} 
curl() { # entry point for curl-head, curl-get, curl-post 
  commands  
} 
main() { 
  ## rewrite url if needed etc 
  ( # curl head request 
    if-options() { 
      cat << EOF 
--location 
EOF 
    } 
    curl head ${url} > head-response 
  ) 
  test "$( cat head-response | grep -e ‘Location:’ )" || { 
    ## block reassigning url base on head response location 
    url=…  
  } 
  reset-curl 
  ## setup curl ... 
  curl get ${url} # > get-response 
  extract-info-for-post-request # < get-reponse, extracts token and other info for post 
  ## reset curl and setup if needed … 
  curl post ${url} # > post-response 
} 
curl-example() {
 true
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
curl-example
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 27 Jan 2019 16:36:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
