#!/bin/bash
## curl-basic-auth-config
## version 0.0.1 - initial
##################################################
username="username"
password="passwd"
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 27 Jan 2019 14:08:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
