#!/bin/bash 
## curl-retry 
## - retries curl indefinitely 
## version 0.0.1 
################################################## 
car() { 
  echo "${1}" 
} 
curl-error-code() { 
  test ! -f "curl-error" || { 
   car $( 
    cat curl-error \ 
    | sed \ 
      -e 's/[^0-9 ]//g' 
   ) 
  } 
} 
curl-retry() { 
  while [ ! ]  
  do 
    curl temptemp3.sh 2>curl-error || { 
      case $( curl-error-code ) in 
      6) { 
       ## handle error code 6 
       echo curl unable to resolve host 
      } ;; 
      *) { 
       # <https://curl.haxx.se/libcurl/c/libcurl-errors.html> 
       true # not yet implemented 
      } ;; 
      esac 
      sleep 1 
      continue 
    } 
    break 
  done 
} 
################################################## 
if [ ${#} -eq 0 ]  
then 
true 
else 
exit 1 # wrong args 
fi 
################################################## 
curl-retry 
################################################## 
## generated by create-stub2.sh v0.1.1 
## on Sun, 27 Jan 2019 15:58:51 +0900 
## see <https://github.com/temptemp3/sh2> 
################################################## 
