#!/bin/bash
## debug-random-error
## version 0.0.1 - initial
##################################################
debug-random-error() { 
  test $(( ${RANDOM} % 2 )) -eq 0
  echo success
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
debug-random-error
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 20 May 2019 21:40:46 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
