#!/bin/bash
## debug-options
## version 0.0.1 - initial
##################################################
debug-options() {
 #################################################
 echo ${FUNCNAME^^}
 #################################################
 ## 1. set -x
 ## 1. set -v
 ## 1. set -e
 #################################################
 ## 1. set -x, set -v		  #
 test 0 -eq 0	# were invisible  #
 echo -n ""	# 		  #
 set -x -v 	# wax on 	  #
 test 0 -eq 0	# now are visible # + test 0 -eq 0
 echo -n ""	# 		  # + echo -n ''
 set +x +v 	# wax off	  # + set +x +y
 #################################################
 ## 1. set -e
 set -e
 test ! 0 -eq 0 || true # does not echo done
 			# i.e. exits with status 1
			# without || true
 test ! 0 -eq 0 || {
   # may provide useful debug info here before
   # exiting script with exit status as error
   false || true # without || true
 }
 set +e
 #################################################
 echo done
 #################################################
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
debug-options
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 20 May 2019 21:59:34 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
