#!/bin/bash
## join
## version 0.0.2 - fix recursion parameters
##################################################
join() { { local indelimiter; indelimiter="${1- }" ; local outdelimiter; outdelimiter="${2-.}" ; }
  local car
  local cdr
  local IFS
  IFS="${indelimiter}"
  read -t 1 car cdr || return
  test "${cdr}" || { echo "${car}" ; return ; }
  echo "${car}${outdelimiter}${cdr}" | ${FUNCNAME} "${indelimiter}" "${outdelimiter}"
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 17 Jun 2019 12:24:59 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
