#!/bin/bash
## map
## version 0.0.1 - initial
##################################################
map() { { local function_name ; function_name="${1}" ; }
  local car 
  local cdr 
  local IFS 
  IFS="${indelimiter- }" 
  read -t 1 car cdr || return 
  test "$( declare -f ${function_name} )" || return
  test "${car}" || { true ; return ; }
  ${function_name} ${car}
  echo "${cdr}" | ${FUNCNAME} "${function_name}"
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 18 Jun 2019 08:33:49 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
