#!/bin/bash
## subshell-functions
## version 0.0.1 - initial
##################################################
d() { true ; }
c() { true ; }
b() { true ; }
a() {
  { b ; c ; d ; }
  (
    b() {
      cat << EOF
I am b
EOF
    }
    { b ; c ; d ; }
  )
  { b ; c ; d ; }
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
a
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 27 Jan 2019 13:43:50 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
