#!/bin/bash
## test-square-matrix
## - generates square matrices up to 10 x 10
## version 0.0.1 - initial
##################################################
test-square-matrix() {
  test -f "square-matrix.sh"
  . ${_} 1>/dev/null
  local i
  for i in {1..10}
  do
   echo "square-matrix(${i})"
   square-matrix ${i}
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-square-matrix
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 29 May 2019 13:40:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
