#!/bin/bash
## test-random-ips
## version 0.0.1 - initial
##################################################
. ${SH2}/cecho.sh
test-random-ips-template() {
  { # template
    cecho green "${message} ..."
    local method
    local size
    time for size in ${sizes}
    do
     cecho yellow size: ${size}
     time for method in ${methods}
     do
      cecho yellow method: ${method}
      time random-ips ${size} ${method}
     done
    done
    cecho green "done ${message}"
  } 1>/dev/null
}
test-random-ips-1() {
  { # time (1) all
    local sizes
    local methods
    local message
    sizes="1 10 100"
    methods="1 2"
    message="timing serial methods"
    test-random-ips-template
  } 1>/dev/null
}
test-random-ips-2() {
  { # time (2) parallel
    local sizes
    local methods
    local message
    sizes="100 250 500"
    methods="3 4"
    message="timing parallel methods"
    test-random-ips-template
  } 1>/dev/null
}
test-random-ips-3() {
  { # time (3) 1k
    cecho green "generating 1k random ip addresses ..."
    time random-ips 1000 4 1>/dev/null
    cecho green "done generating 1k random ip addresses"
  }
}
test-random-ips() {
  local tests
  tests=3
  { # import
    cecho green loading random-ips.sh
    test -f "${_}" || return
    . ${_} &>/dev/null
    cecho green done loading ${_}
  }
  { # run tests
    cecho green "running tests ..."
    local i
    time for i in $( seq ${tests} )
    do
     ${FUNCNAME}-${i}
    done
    cecho green "done running tests"
  }
  true
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-random-ips
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 11 Jun 2019 14:11:07 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
