#!/bin/bash
## test-random-ips
## version 0.0.1 - initial
##################################################
. ${SH2}/cecho.sh
test-random-ips-template() {
  { # tempalte
    local method
    local size
    for size in ${sizes}
    do
     cecho yellow size: ${size}
     for method in ${methods}
     do
      cecho yellow method: ${method}
      time random-ips ${size} ${method}
     done
    done
  } 1>/dev/null
}
test-random-ips-1() {
  { # time (1) all
    local sizes
    local methods
    sizes=(1 10 100)
    methods={1..4}
    cecho green "timing all methods ..."
    test-random-ips-template
    cecho green "methods timed"
  } 1>/dev/null
}
test-random-ips-2() {
  { # time (2) parallel
    cecho green "timing parallel methods ..."
    local method
    local size
    for size in 100 500 1000
    do
     cecho yellow size: ${size}
     for method in {3..4}
     do
      cecho yellow method: ${method}
      time random-ips ${size} ${method}
     done
    done
    cecho green "methods timed"
  } 1>/dev/null
}
test-random-ips-3() {
  { # time (3) 10k
    cecho green "generating 10k random ips addresses ..."
    time random-ips 10000 4 1>/dev/null
    cecho green "done"
  }
}
test-random-ips() {
  local tests
  tests=3
  { # import
    cecho green loading random-ips.sh
    test -f "${_}" || return
    . ${_} &>/dev/null
    cecho green done loading ${_}
  }
  { # run tests
    local i
    for i in 3 #$( seq ${tests} )
    do
     ${FUNCNAME}-${i}
    done
  }
  true
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-random-ips
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 11 Jun 2019 14:11:07 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
