#!/bin/bash
## test-export-inspect
## version 0.0.1 - initial
##################################################
test-export-inspect() {
  test ! "$( export -f | grep eval )" || { 
    echo chaos detect 1>&2
    echo exiting script ... 1>&2
    exit 2 # chaos
  }
  echo life is good
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-export-inspect
##################################################
## generated by create-stub2.sh v0.1.2
## on Sun, 07 Jul 2019 16:40:13 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
