#!/bin/bash
## test-random-ips
## version 0.0.1 - initial
##################################################
test-random-ips() {
  test -f "random-ips.sh" || return
  . ${_} &>/dev/null
  {
    time random-ips 100 1
    time random-ips 100 2
    time random-ips 100 3
    time random-ips 100 4
  } 1>/dev/null
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-random-ips
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 11 Jun 2019 14:11:07 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
