#!/bin/bash
## test-export-xargs
## version 0.0.1 - initial
##################################################
test-export-xargs() {
  fun() { 
    echo A${@}
  }
  export -f fun
  seq 9 | xargs -i bash -c "fun {}" | xargs
  seq 9 | xargs -i echo "fun {}" | bash | xargs
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-export-xargs
##################################################
## generated by create-stub2.sh v0.1.2
## on Fri, 05 Jul 2019 22:47:19 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
