#!/bin/bash
## true
## version 0.0.3 - fix
##################################################
declare -f "true" &>/dev/null || {
  true() {
   command true
  }
}
##################################################
if [ ${#} -eq 0 ] 
then
 command true
else
 exit 1 # wrong args
fi
##################################################
true
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 01 Jul 2019 13:48:43 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
