#!/bin/bash
## test-linuxhint-list-bash-programming
## version 0.0.1 - initial
##################################################
test-linuxhint-list-bash-programming() {
  local url
  local line
  local title
  local href
  url="https://linuxhint.com/category/bash-programming/page/[1-99]/"
  curl --silent --url "${url}" |
  grep --line-number -e 'entry-title' | while read -r line
  do
   _() {
     echo ${line} | 
     grep --only-matching -e "${1}=\"[^\"]*" |
     cut '-d"' '-f2'
   }
   echo ${line} 1>&2
   ## setup
   title=$( _ title )
   href=$( _ href )
   ## guards
   test "${title}" || continue
   test "${href}" || continue
   echo "+ [$( _ title )]($( _ href ))"
  done | sort
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-linuxhint-list-bash-programming
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 27 May 2019 20:22:43 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
